### ISSUE TITLE
Doesn't display chat bubble

### ISSUE THREAD

**Issue by Tomucha** [Crdzbird/floaty_chathead#7]
... I tried to implement this plugin into my app, but without any success. I see an "ongoing" notification, but nothing similar to chat bubbles.

Then I cloned the repository and tried to run the example as it is, but the same result. All I can see is the notification, but nothing else.

```
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (5 weeks ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

```

Also - plugin generates a lot of exceptions, even the example:

```
E/flutter ( 9710): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'FutureOr<int>' in type cast
E/flutter ( 9710): #0      FloatyHead.setCloseIcon (package:floaty_head/floaty_head.dart:179:9)
E/flutter ( 9710): #1      _Home.setCloseIcon (package:floaty_head_example/main.dart:300:24)
E/flutter ( 9710): #2      _Home.build.<anonymous closure> (package:floaty_head_example/main.dart:227:36)
E/flutter ( 9710): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)

```

**Comment by askavinraja** [comment]
Same problem

**Comment by Leleocastro** [comment]
Same here.

**Comment by Leleocastro** [comment]
I guess this is the solution.
[](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration)

**Comment by Leleocastro** [comment]
I found a solution for the chat bubble, for some reason the function createWindow in the onCreate in FloatyContentJobService.kt was not called.

**Comment by Chris-Benn** [comment]
Does anyone have a solution to this problem, i am having it as well

**Comment by Chris-Benn** [comment]
Hello
Where is this  onCreate in FloatyContentJobService.kt located 
> I found a solution for the chat bubble, for some reason the function createWindow in the onCreate in FloatyContentJobService.kt was not called.
> 
> EDIT:
> Was not called because that will crashes the app, but the problem it's the version of Android.

**Comment by Leleocastro** [comment]
@Chris-Benn,
I downloaded the package and edited in my local machine. You'll need to look into kotlin(android) files.

FloatyContentJobService bellow:
[https://github.com/Crdzbird/floaty_chathead/blob/master/android/src/main/kotlin/ni/devotion/floaty_head/services/FloatyContentJobService.kt](url)

**Comment by Chris-Benn** [comment]
@Leleocastro 
thanks, can you share what the changes where on the page


> @Chris-Benn,
> I downloaded the package and edited in my local machine. You'll need to look into kotlin(android) files.
> 
> FloatyContentJobService bellow:
> [https://github.com/Crdzbird/floaty_chathead/blob/master/android/src/main/kotlin/ni/devotion/floaty_head/services/FloatyContentJobService.kt](url)

**Comment by Chris-Benn** [comment]
@Leleocastro
thanks, finally got it....
